# Generated by Django 4.2 on 2023-04-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_availability',
            new_name='is_available',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./media/'),
        ),
    ]
